apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
spec:
  containers:
    - name: mysql-container
      image: 139675527364.dkr.ecr.us-east-1.amazonaws.com/k8s-assignment:mysql
      ports:
        - containerPort: 3306
