apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mysql-replicaset
  labels:
    app: mysql
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: 329921743825.dkr.ecr.us-east-1.amazonaws.com/mydb:v2.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
        ports:
         - containerPort: 8080
           protocol: TCP
