apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mysql
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/component: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: mysql
      app.kubernetes.io/component: backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mysql
        app.kubernetes.io/component: backend
    spec:
      containers:
      - name: mysql
        image: 139675527364.dkr.ecr.us-east-1.amazonaws.com/k8s-assignment:mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
        ports:
         - containerPort: 3306
           protocol: TCP
