apiVersion: v1
kind: Service
metadata:
  name: webserver
  labels:
    app.kubernetes.io/name: webserver
    app.kubernetes.io/component: frontend
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30000
  selector:
    app.kubernetes.io/name: webserver
    app.kubernetes.io/component: frontend
