apiVersion: v1
kind: Pod
metadata:
  name: webserver
  labels:
    app.kubernetes.io/name: webserver
    app.kubernetes.io/component: frontend
spec:
  containers:
  - name: webserver
    image: 139675527364.dkr.ecr.us-east-1.amazonaws.com/k8s-assignment:app # Replace with your image repository and image name
    env:
    - name: DBHOST
      value: mysql-service  # Replace with the hostname of your MySQL service
    - name: DBUSER
      value: root
    - name: DBPWD
      value: password  # Replace with your MySQL password
    - name: DATABASE
      value: employees  # Replace with your MySQL database name
    - name: APP_COLOR
      value: lime  # Replace with the desired color
    ports:
    - containerPort: 80
      protocol: TCP
    
