apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: web-replicaset
  labels:
    app.kubernetes.io/name: webserver
    app.kubernetes.io/component: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: webserver
      app.kubernetes.io/component: frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: webserver
        app.kubernetes.io/component: frontend
    spec:
      containers:
      - name: webserver
        ports:
          - containerPort: 8080
            protocol: TCP
        image: 139675527364.dkr.ecr.us-east-1.amazonaws.com/k8s-assignment:app
        env:
        - name: DBHOST
          value: mysql.webserver.svc.cluster.local  # Replace with the hostname of your MySQL service
        - name: DBUSER
          value: root
        - name: DBPWD
          value: password  # Replace with your MySQL password
        - name: DATABASE
          value: employees  # Replace with your MySQL database name
        - name: APP_COLOR
          value: blue  # Replace with the desired color
